/*
 * Copyright 2008-2010 Austrian Institute of Technology
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they
 * will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence");
 * you may not use this work except in compliance with the
 * Licence.
 * You may obtain a copy of the Licence at:
 *
 * http://ec.europa.eu/idabc/eupl
 *
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
 */

package at.ait.dme.yuma.suite.test.test;

import org.junit.Test;

public class ImageAnnotationBuilderTest {

	/*
	private ImageAnnotation createAnnotation() {
		// annotation w/ polygon fragment
		ImageAnnotation annotation = new ImageAnnotation();
		annotation.setObjectId("http://objectid");
		annotation.setCreatedBy("user");
		annotation.setTitle("title");
		annotation.setText("text");
		annotation.setScope(Scope.PUBLIC);
		
		Collection<Point> points = new ArrayList<Point>();
		points.add(new Point(350,75));
		points.add(new Point(379,161));
		points.add(new Point(469,161));
		points.add(new Point(397,215));
		
		Shape shape = new Polygon(0,0,100,120,new Color(0,120,255),1, points);
		ImageFragment fragment = new ImageFragment(
				new ImageRect(0,0,499,223),
				new ImageRect(-20,-30,700,400),
				shape);
		annotation.setFragment(fragment);
		annotation.setType(Type.IMAGE);
		
		// add reply w/ rectangle fragment
		ImageAnnotation reply = new ImageAnnotation();
		reply.setObjectId("http://objectid");
		reply.setCreatedBy("user reply");
		reply.setTitle("title reply");
		reply.setText("text reply");
		reply.setScope(Scope.PUBLIC);
		
		Shape shapeReply = new Rectangle(0,0,100,100,new Color(0,120,255),1);
		ImageFragment fragmentReply = new ImageFragment(
				new ImageRect(0,0,499,223),
				new ImageRect(-20,-30,700,400),			
				shapeReply);
		reply.setFragment(fragmentReply);	
		
		annotation.addReply(reply);	
		
		// add reply w/ ellipse fragment
		ImageAnnotation reply2 = new ImageAnnotation();
		reply2.setObjectId("http://objectid");
		reply2.setCreatedBy("user reply2");
		reply2.setTitle("title reply2");
		reply2.setText("text reply2");
		reply.setScope(Scope.PUBLIC);
		
		Shape shapeReply2 = new Ellipse(0,0,100,100,new Color(0,120,255),1);
		ImageFragment fragmentReply2 = new ImageFragment(
				new ImageRect(0,0,499,223),
				new ImageRect(-20,-30,700,400),			
				shapeReply2);
		reply2.setFragment(fragmentReply2);	
		
		annotation.addReply(reply2);	
		
		// add reply to the reply w/ cross fragment
		ImageAnnotation replyReply = new ImageAnnotation();
		replyReply.setObjectId("http://objectid");
		replyReply.setCreatedBy("user reply reply");
		replyReply.setTitle("title reply reply");
		replyReply.setText("text reply reply");
		replyReply.setScope(Scope.PRIVATE);
		
		Cross shapeReplyReply = new Cross(0,0,100,100,new Color(0,120,255),1);
		ImageFragment fragmentReplyReply = new ImageFragment(
				new ImageRect(0,0,499,223),
				new ImageRect(-20,-30,700,400),			
				shapeReplyReply);
		replyReply.setFragment(fragmentReplyReply);	
		
		reply.addReply(replyReply);
		
		// add reply to the reply w/o fragment
		ImageAnnotation replyReply2 = new ImageAnnotation();
		replyReply2.setObjectId("http://objectid");
		replyReply2.setCreatedBy("user reply reply");
		replyReply2.setTitle("title reply reply");
		replyReply2.setText("text reply reply");
		replyReply2.setScope(Scope.PRIVATE);
		
		reply.addReply(replyReply2);
		
		return annotation;
	}
	
	private ImageAnnotation createGeoPointAnnotation() {
		ImageFragment fragment = new ImageFragment(
				new ImageRect(0, 0, 10492, 11908),
				new ImageRect(-20, -30, 10462, 11888),
				new GeoPoint("Aruba", 4460, 6553, 12.478056909259756, -69.93896484375));
		
		// id is just for testing, will be generated by db
		ImageAnnotation annotation = new ImageAnnotation();
		annotation.setObjectId("http://urlToMap");
		annotation.setCreatedBy("user");
		annotation.setFragment(fragment);
		
		// optionally we could set title and text
		annotation.setTitle("controlpoint");
		annotation.setText("This is a controlpoint for Aruba on the Map of the Americas by Diego Guiterrez");
		
		return annotation;
	}
	*/
	
	@Test
	public void testJson() {		
		/*
		ImageAnnotation annotation = createAnnotation();
		
		String jsonAnnotation=JSONAnnotationBuilder.toJson(annotation);		
		Collection<Annotation> annotations = JSONAnnotationBuilder.fromJson(jsonAnnotation);
		
		assertEquals(annotations.iterator().next(),annotation);
		*/						
	}
	
	/*
	@Test
	public void testRdfXml() throws RepositoryException, RDFHandlerException, IOException, 
		RDFParseException {
		
		ImageAnnotation annotation = createAnnotation();

		String rdfXmlAnnotation = RdfXmlAnnotationBuilder.toRdfXml(annotation);
		Collection<ImageAnnotation> annotations=
			RdfXmlAnnotationBuilder.fromRdfXml(rdfXmlAnnotation);				
		assertEquals(annotations.iterator().next(), annotation);
		
		annotation = createGeoPointAnnotation();
		rdfXmlAnnotation = RdfXmlAnnotationBuilder.toRdfXml(annotation);
		annotations = RdfXmlAnnotationBuilder.fromRdfXml(rdfXmlAnnotation);				
		assertEquals(annotations.iterator().next(), annotation);
		
		annotations=RdfXmlAnnotationBuilder.fromRdfXml(null);		
		assertTrue(annotations.isEmpty());
		
		annotations=RdfXmlAnnotationBuilder.fromRdfXml("");		
		assertTrue(annotations.isEmpty());
	}
	*/
	
	/*
	@Test
	public void testAnnotationWithoutFragment() throws Exception {
		ImageAnnotation annotation = new ImageAnnotation("http://id", "http://objectid",
				null, null, "user", "title", "text",
				ImageAnnotation.Scope.PUBLIC);
		
		String jsonAnnotation = JSONAnnotationBuilder.toJson(annotation);
		Collection<Annotation> jsonAnnotations=
			JSONAnnotationBuilder.fromJson(jsonAnnotation);				
		assertEquals(jsonAnnotations.iterator().next(), annotation);
		
		String rdfXmlAnnotation = RdfXmlAnnotationBuilder.toRdfXml(annotation);
		Collection<ImageAnnotation> rdfAnnotations = RdfXmlAnnotationBuilder.fromRdfXml(rdfXmlAnnotation);				
		assertEquals(rdfAnnotations.iterator().next(), annotation);
		
		ImageAnnotation a = rdfAnnotations.iterator().next();
		assertEquals(a.getFragment(), new ImageFragment());
		assertTrue(((ImageFragment)a.getFragment()).getShape() instanceof VoidShape);
		assertEquals(((ImageFragment)a.getFragment()).getShape(), new VoidShape());	
	}
	*/
	
}
